apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calibration1
  name: calibration1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibration1
  template:
    metadata:
      labels:
        app: calibration1
    spec:
      containers:
      - image: docker.io/tsveiga/ai4iot:calibration
        imagePullPolicy: Always
        name: calibration1
        ports:
        - containerPort: 8061
          name: protobuf-api
        - containerPort: 8062
          name: webui
      imagePullSecrets:
      - name: acumos-registry
