apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-source1
  name: data-source1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-source1
  template:
    metadata:
      labels:
        app: data-source1
    spec:
      containers:
      - image: docker.io/tsveiga/ai4iot:datasource
        imagePullPolicy: Always
        name: data-source1
        ports:
        - containerPort: 8061
          name: protobuf-api
        - containerPort: 8062
          name: webui
      imagePullSecrets:
      - name: acumos-registry
