# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='aqpredictions',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmodel.proto\x12\raqpredictions\"\x07\n\x05\x45mpty\"\xc5\x01\n\x0e\x41QTrainRequest\x12\x0f\n\x07station\x18\x01 \x01(\t\x12\x11\n\tpollutant\x18\x02 \x01(\t\x12\x11\n\tthreshold\x18\x03 \x01(\x05\x12\x14\n\x0cuse_temporal\x18\x04 \x01(\x08\x12\x11\n\tuse_delta\x18\x05 \x01(\x08\x12\x13\n\x0buse_only_pm\x18\x06 \x01(\x08\x12\x13\n\x0buse_weather\x18\x07 \x01(\x08\x12\x14\n\x0cuse_forecast\x18\x08 \x01(\x08\x12\x13\n\x0buse_traffic\x18\t \x01(\x08\"P\n\x0f\x41QTrainResponse\x12\x13\n\x0btest_recall\x18\x01 \x01(\x02\x12\x16\n\x0etest_precision\x18\x02 \x01(\x02\x12\x10\n\x08test_roc\x18\x03 \x01(\x02\"\x9c\x01\n\x10\x41QPredictRequest\x12\x16\n\x0e\x65\x36_tiller_pm25\x18\x01 \x01(\x02\x12\x16\n\x0e\x65\x36_tiller_pm10\x18\x02 \x01(\x02\x12\x16\n\x0e\x65lgeseter_pm25\x18\x03 \x01(\x02\x12\x16\n\x0e\x65lgeseter_pm10\x18\x04 \x01(\x02\x12\x13\n\x0btorvet_pm25\x18\x05 \x01(\x02\x12\x13\n\x0btorvet_pm10\x18\x06 \x01(\x02\"/\n\x11\x41QPredictResponse\x12\x1a\n\x12predicted_aq_level\x18\x01 \x01(\t2\xb2\x01\n\x06\x41I4IoT\x12Q\n\x10train_classifier\x12\x1d.aqpredictions.AQTrainRequest\x1a\x1e.aqpredictions.AQTrainResponse\x12U\n\x10predict_aq_level\x12\x1f.aqpredictions.AQPredictRequest\x1a .aqpredictions.AQPredictResponseb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='aqpredictions.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=37,
)


_AQTRAINREQUEST = _descriptor.Descriptor(
  name='AQTrainRequest',
  full_name='aqpredictions.AQTrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='station', full_name='aqpredictions.AQTrainRequest.station', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pollutant', full_name='aqpredictions.AQTrainRequest.pollutant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='aqpredictions.AQTrainRequest.threshold', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_temporal', full_name='aqpredictions.AQTrainRequest.use_temporal', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_delta', full_name='aqpredictions.AQTrainRequest.use_delta', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_only_pm', full_name='aqpredictions.AQTrainRequest.use_only_pm', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_weather', full_name='aqpredictions.AQTrainRequest.use_weather', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_forecast', full_name='aqpredictions.AQTrainRequest.use_forecast', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_traffic', full_name='aqpredictions.AQTrainRequest.use_traffic', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=237,
)


_AQTRAINRESPONSE = _descriptor.Descriptor(
  name='AQTrainResponse',
  full_name='aqpredictions.AQTrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_recall', full_name='aqpredictions.AQTrainResponse.test_recall', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_precision', full_name='aqpredictions.AQTrainResponse.test_precision', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_roc', full_name='aqpredictions.AQTrainResponse.test_roc', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=319,
)


_AQPREDICTREQUEST = _descriptor.Descriptor(
  name='AQPredictRequest',
  full_name='aqpredictions.AQPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='e6_tiller_pm25', full_name='aqpredictions.AQPredictRequest.e6_tiller_pm25', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e6_tiller_pm10', full_name='aqpredictions.AQPredictRequest.e6_tiller_pm10', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elgeseter_pm25', full_name='aqpredictions.AQPredictRequest.elgeseter_pm25', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elgeseter_pm10', full_name='aqpredictions.AQPredictRequest.elgeseter_pm10', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torvet_pm25', full_name='aqpredictions.AQPredictRequest.torvet_pm25', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torvet_pm10', full_name='aqpredictions.AQPredictRequest.torvet_pm10', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=478,
)


_AQPREDICTRESPONSE = _descriptor.Descriptor(
  name='AQPredictResponse',
  full_name='aqpredictions.AQPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predicted_aq_level', full_name='aqpredictions.AQPredictResponse.predicted_aq_level', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=527,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AQTrainRequest'] = _AQTRAINREQUEST
DESCRIPTOR.message_types_by_name['AQTrainResponse'] = _AQTRAINRESPONSE
DESCRIPTOR.message_types_by_name['AQPredictRequest'] = _AQPREDICTREQUEST
DESCRIPTOR.message_types_by_name['AQPredictResponse'] = _AQPREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:aqpredictions.Empty)
  })
_sym_db.RegisterMessage(Empty)

AQTrainRequest = _reflection.GeneratedProtocolMessageType('AQTrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _AQTRAINREQUEST,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:aqpredictions.AQTrainRequest)
  })
_sym_db.RegisterMessage(AQTrainRequest)

AQTrainResponse = _reflection.GeneratedProtocolMessageType('AQTrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _AQTRAINRESPONSE,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:aqpredictions.AQTrainResponse)
  })
_sym_db.RegisterMessage(AQTrainResponse)

AQPredictRequest = _reflection.GeneratedProtocolMessageType('AQPredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _AQPREDICTREQUEST,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:aqpredictions.AQPredictRequest)
  })
_sym_db.RegisterMessage(AQPredictRequest)

AQPredictResponse = _reflection.GeneratedProtocolMessageType('AQPredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _AQPREDICTRESPONSE,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:aqpredictions.AQPredictResponse)
  })
_sym_db.RegisterMessage(AQPredictResponse)



_AI4IOT = _descriptor.ServiceDescriptor(
  name='AI4IoT',
  full_name='aqpredictions.AI4IoT',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=530,
  serialized_end=708,
  methods=[
  _descriptor.MethodDescriptor(
    name='train_classifier',
    full_name='aqpredictions.AI4IoT.train_classifier',
    index=0,
    containing_service=None,
    input_type=_AQTRAINREQUEST,
    output_type=_AQTRAINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='predict_aq_level',
    full_name='aqpredictions.AI4IoT.predict_aq_level',
    index=1,
    containing_service=None,
    input_type=_AQPREDICTREQUEST,
    output_type=_AQPREDICTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AI4IOT)

DESCRIPTOR.services_by_name['AI4IoT'] = _AI4IOT

# @@protoc_insertion_point(module_scope)
