# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='data_client',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63lient.proto\x12\x0b\x64\x61ta_client\x1a\x1bgoogle/protobuf/empty.proto\"\xc2\x01\n\nDataSample\x12\x0b\n\x03pm1\x18\x01 \x01(\x02\x12\x0c\n\x04pm25\x18\x02 \x01(\x02\x12\x0c\n\x04pm10\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ir_temperature\x18\x04 \x01(\x02\x12\x19\n\x11relative_humidity\x18\x05 \x01(\x02\x12\x15\n\rprecipitation\x18\x06 \x01(\x02\x12\x14\n\x0c\x61ir_pressure\x18\x07 \x01(\x02\x12\x12\n\nwind_speed\x18\x08 \x01(\x02\x12\x16\n\x0ewind_direction\x18\t \x01(\x02\"G\n\x11\x43lientInitRequest\x12\x0f\n\x07iot_api\x18\x01 \x01(\t\x12\x11\n\tiot_token\x18\x02 \x01(\t\x12\x0e\n\x06met_id\x18\x03 \x01(\t2\x95\x01\n\nDataClient\x12\x45\n\x0binit_client\x12\x1e.data_client.ClientInitRequest\x1a\x16.google.protobuf.Empty\x12@\n\rget_last_data\x12\x16.google.protobuf.Empty\x1a\x17.data_client.DataSampleb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DATASAMPLE = _descriptor.Descriptor(
  name='DataSample',
  full_name='data_client.DataSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pm1', full_name='data_client.DataSample.pm1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pm25', full_name='data_client.DataSample.pm25', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pm10', full_name='data_client.DataSample.pm10', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='air_temperature', full_name='data_client.DataSample.air_temperature', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relative_humidity', full_name='data_client.DataSample.relative_humidity', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precipitation', full_name='data_client.DataSample.precipitation', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='air_pressure', full_name='data_client.DataSample.air_pressure', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='data_client.DataSample.wind_speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_direction', full_name='data_client.DataSample.wind_direction', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=253,
)


_CLIENTINITREQUEST = _descriptor.Descriptor(
  name='ClientInitRequest',
  full_name='data_client.ClientInitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='iot_api', full_name='data_client.ClientInitRequest.iot_api', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iot_token', full_name='data_client.ClientInitRequest.iot_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='met_id', full_name='data_client.ClientInitRequest.met_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=326,
)

DESCRIPTOR.message_types_by_name['DataSample'] = _DATASAMPLE
DESCRIPTOR.message_types_by_name['ClientInitRequest'] = _CLIENTINITREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataSample = _reflection.GeneratedProtocolMessageType('DataSample', (_message.Message,), {
  'DESCRIPTOR' : _DATASAMPLE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:data_client.DataSample)
  })
_sym_db.RegisterMessage(DataSample)

ClientInitRequest = _reflection.GeneratedProtocolMessageType('ClientInitRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINITREQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:data_client.ClientInitRequest)
  })
_sym_db.RegisterMessage(ClientInitRequest)



_DATACLIENT = _descriptor.ServiceDescriptor(
  name='DataClient',
  full_name='data_client.DataClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=329,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='init_client',
    full_name='data_client.DataClient.init_client',
    index=0,
    containing_service=None,
    input_type=_CLIENTINITREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_last_data',
    full_name='data_client.DataClient.get_last_data',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DATASAMPLE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATACLIENT)

DESCRIPTOR.services_by_name['DataClient'] = _DATACLIENT

# @@protoc_insertion_point(module_scope)
