apiVersion: v1
kind: Service
metadata:
  name: data-source1webui
spec:
  ports:
  - name: webui
    nodePort: 30007
    port: 30007
    targetPort: 8062
  selector:
    app: data-source1
  type: NodePort
