apiVersion: v1
kind: Service
metadata:
  name: data-source1
spec:
  ports:
  - name: protobuf-api
    nodePort: 30006
    port: 30006
    targetPort: 8061
  selector:
    app: data-source1
  type: NodePort
