apiVersion: v1
kind: Service
metadata:
  name: visualization1
spec:
  ports:
  - name: protobuf-api
    nodePort: 30000
    port: 30000
    targetPort: 8061
  selector:
    app: visualization1
  type: NodePort
