apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visualization1
  name: visualization1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization1
  template:
    metadata:
      labels:
        app: visualization1
    spec:
      containers:
      - image: docker.io/tsveiga/ai4iot:visualization
        imagePullPolicy: Always
        name: visualization1
        ports:
        - containerPort: 8061
          name: protobuf-api
        - containerPort: 8062
          name: webui
      imagePullSecrets:
      - name: acumos-registry
