# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calibration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calibration.proto',
  package='aqcalibration',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63\x61libration.proto\x12\raqcalibration\"\xc2\x01\n\nDataSample\x12\x0b\n\x03pm1\x18\x01 \x01(\x02\x12\x0c\n\x04pm25\x18\x02 \x01(\x02\x12\x0c\n\x04pm10\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ir_temperature\x18\x04 \x01(\x02\x12\x19\n\x11relative_humidity\x18\x05 \x01(\x02\x12\x15\n\rprecipitation\x18\x06 \x01(\x02\x12\x14\n\x0c\x61ir_pressure\x18\x07 \x01(\x02\x12\x12\n\nwind_speed\x18\x08 \x01(\x02\x12\x16\n\x0ewind_direction\x18\t \x01(\x02\"A\n\rCalibResponse\x12\x17\n\x0f\x63\x61librated_pm25\x18\x01 \x01(\x02\x12\x17\n\x0f\x63\x61librated_pm10\x18\x02 \x01(\x02\x32Z\n\x0b\x43\x61libration\x12K\n\x10\x63\x61librate_sample\x12\x19.aqcalibration.DataSample\x1a\x1c.aqcalibration.CalibResponseb\x06proto3'
)




_DATASAMPLE = _descriptor.Descriptor(
  name='DataSample',
  full_name='aqcalibration.DataSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pm1', full_name='aqcalibration.DataSample.pm1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pm25', full_name='aqcalibration.DataSample.pm25', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pm10', full_name='aqcalibration.DataSample.pm10', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='air_temperature', full_name='aqcalibration.DataSample.air_temperature', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relative_humidity', full_name='aqcalibration.DataSample.relative_humidity', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precipitation', full_name='aqcalibration.DataSample.precipitation', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='air_pressure', full_name='aqcalibration.DataSample.air_pressure', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='aqcalibration.DataSample.wind_speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_direction', full_name='aqcalibration.DataSample.wind_direction', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=231,
)


_CALIBRESPONSE = _descriptor.Descriptor(
  name='CalibResponse',
  full_name='aqcalibration.CalibResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibrated_pm25', full_name='aqcalibration.CalibResponse.calibrated_pm25', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calibrated_pm10', full_name='aqcalibration.CalibResponse.calibrated_pm10', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=298,
)

DESCRIPTOR.message_types_by_name['DataSample'] = _DATASAMPLE
DESCRIPTOR.message_types_by_name['CalibResponse'] = _CALIBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataSample = _reflection.GeneratedProtocolMessageType('DataSample', (_message.Message,), {
  'DESCRIPTOR' : _DATASAMPLE,
  '__module__' : 'calibration_pb2'
  # @@protoc_insertion_point(class_scope:aqcalibration.DataSample)
  })
_sym_db.RegisterMessage(DataSample)

CalibResponse = _reflection.GeneratedProtocolMessageType('CalibResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRESPONSE,
  '__module__' : 'calibration_pb2'
  # @@protoc_insertion_point(class_scope:aqcalibration.CalibResponse)
  })
_sym_db.RegisterMessage(CalibResponse)



_CALIBRATION = _descriptor.ServiceDescriptor(
  name='Calibration',
  full_name='aqcalibration.Calibration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=300,
  serialized_end=390,
  methods=[
  _descriptor.MethodDescriptor(
    name='calibrate_sample',
    full_name='aqcalibration.Calibration.calibrate_sample',
    index=0,
    containing_service=None,
    input_type=_DATASAMPLE,
    output_type=_CALIBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALIBRATION)

DESCRIPTOR.services_by_name['Calibration'] = _CALIBRATION

# @@protoc_insertion_point(module_scope)
